name: disease_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  firebase_core: ^2.27.1
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cloud_firestore: ^4.15.9

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
      